Instance_name       of model        Regenerate status

PULLEY-PARA-NO-HOLE_8M-20-BIGPULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_8M-52PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE-8M-50PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_8M-20PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_24-3MPULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_44PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_3M-24PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_3M-48PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_17-BIGPULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_17PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_21-3MPULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_45PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_25PULLEY-PARA-NO-HOLE Success
PULLEY-PARA-NO-HOLE_60PULLEY-PARA-NO-HOLE Success

